<?php
return [

    // Trattoria l'Isoletta

    [
        "name" => "Spaghetti di zucchine",
        "price" => 10,
        "description" => "Zucchine, pomodoro fresco, basilico, senza glutine",
        "vegan" => true,
        "celiac" => true,
        "available" => true,
        "cover_image" => "images/cibo_9.jpg",
        'category_id' => 2,
        'restaurant_id' => 1,
    ],
    [
        "name" => "Spaghetti con le Vongole",
        "price" => 12,
        "description" => "Vongole fresche, aglio, prezzemolo e un tocco di peperoncino",
        "vegan" => false,
        "celiac" => false,
        "available" => true,
        "cover_image" => "images/cibo_11.jpg",
        'category_id' => 2,
        'restaurant_id' => 1,
    ],
    [
        "name" => "Pennette ai Funghi",
        "price" => 10,
        "description" => "Gustose, senza glutine, con varietà di funghi",
        "vegan" => true,
        "celiac" => true,
        "available" => true,
        "cover_image" => "images/cibo_32.jpg",
        'category_id' => 2,
        'restaurant_id' => 1,
    ],
    [
        "name" => "Insalatona",
        "price" => 8,
        "description" => "Fresca, verde e variegata",
        "vegan" => true,
        "celiac" => true,
        "available" => true,
        "cover_image" => "images/cibo_35.jpg",
        'category_id' => 4,
        'restaurant_id' => 1,
    ],
    [
        "name" => "Insalata di Quinoa",
        "price" => 12,
        "description" => "Quinoa, verdure fresche autoctone, dressing leggero",
        "vegan" => true,
        "celiac" => true,
        "available" => true,
        "cover_image" => "images/cibo_7.jpg",
        'category_id' => 4,
        'restaurant_id' => 1,
    ],
    [
        "name" => "Pizza Margherita",
        "price" => 8,
        "description" => "Pomodoro, mozzarella, basilico, semplice e deliziosa",
        "vegan" => false,
        "celiac" => false,
        "available" => true,
        "cover_image" => "images/cibo_4.jpg",
        'category_id' => 2,
        'restaurant_id' => 1,
    ],
    [
        "name" => "Pizza senza Glutine",
        "price" => 10,
        "description" => "Base senza glutine, ingredienti freschissimi",
        "vegan" => true,
        "celiac" => true,
        "available" => true,
        "cover_image" => "images/cibo_5.jpg",
        'category_id' => 2,
        'restaurant_id' => 1,
    ],


    // Bello Bello

    [
        "name" => "Ravioli Ricotta e Basilico",
        "price" => 12,
        "description" => "Delicati, saporiti, con ripieni cremoso e profumo di basilico",
        "vegan" => false,
        "celiac" => false,
        "available" => true,
        "cover_image" => "images/cibo_31.jpg",
        'category_id' => 2,
        'restaurant_id' => 2,
    ],
    [
        "name" => "Pappardelle al ragù",
        "price" => 12,
        "description" => "Macinato di carne, Pomodoro fresco, pasta fatta in casa",
        "vegan" => false,
        "celiac" => false,
        "available" => true,
        "cover_image" => "images/cibo_1.jpg",
        'category_id' => 2,
        'restaurant_id' => 2,
    ],
    [
        "name" => "Cacio e Pepe",
        "price" => 10,
        "description" => "Semplice, tradizionale, con pecorino romano e pepe nero",
        "vegan" => false,
        "celiac" => false,
        "available" => true,
        "cover_image" => "images/cibo_3.jpg",
        'category_id' => 2,
        'restaurant_id' => 2,
    ],
    [
        "name" => "Grigliata Mista",
        "price" => 20,
        "description" => "Saporita e variegata, con carni e verdure alla brace",
        "vegan" => false,
        "celiac" => false,
        "available" => true,
        "cover_image" => "images/cibo_33.jpg",
        'category_id' => 3,
        'restaurant_id' => 2,
    ],
    [
        "name" => "Patate fritte",
        "price" => 6,
        "description" => "Croccanti, dorate, irresistibili",
        "vegan" => true,
        "celiac" => true,
        "available" => true,
        "cover_image" => "images/cibo_34.jpg",
        'category_id' => 4,
        'restaurant_id' => 2,
    ],
    [
        "name" => "Hamburger",
        "price" => 8,
        "description" => "Gustoso, succulento, con carne di alta qualità",
        "vegan" => false,
        "celiac" => false,
        "available" => true,
        "cover_image" => "images/cibo_20.jpg",
        'category_id' => 3,
        'restaurant_id' => 2,
    ],

    // Pizzeria Napoli
    [
        "name" => "Pizza Green",
        "price" => 10,
        "description" => "Gustosa, senza ingredienti di origine animale",
        "vegan" => true,
        "celiac" => true,
        "available" => true,
        "cover_image" => "images/cibo_18.jpg",
        'category_id' => 2,
        'restaurant_id' => 12,
    ],
    [
        "name" => "Pizza Quattro Stagioni",
        "price" => 11,
        "description" => "Con prosciutto, olive, carciofi e funghi",
        "vegan" => false,
        "celiac" => false,
        "available" => true,
        "cover_image" => "images/cibo_19.jpg",
        'category_id' => 2,
        'restaurant_id' => 12,
    ],
    [
        "name" => "Pizza Margherita",
        "price" => 8,
        "description" => "Pomodoro, mozzarella, basilico, semplice e deliziosa",
        "vegan" => false,
        "celiac" => false,
        "available" => true,
        "cover_image" => "images/cibo_4.jpg",
        'category_id' => 2,
        'restaurant_id' => 12,
    ],
    [
        "name" => "Pizza Diavola",
        "price" => 8,
        "description" => "Piccante, saporita, con peperoncino e salame",
        "vegan" => false,
        "celiac" => false,
        "available" => true,
        "cover_image" => "images/cibo_10.jpg",
        'category_id' => 2,
        'restaurant_id' => 12,
    ],
    [
        "name" => "Patate fritte",
        "price" => 6,
        "description" => "Croccanti, dorate, irresistibili",
        "vegan" => true,
        "celiac" => true,
        "available" => true,
        "cover_image" => "images/cibo_34.jpg",
        'category_id' => 4,
        'restaurant_id' => 12,
    ],

    // Pizzeria Bella Italia

    [
        "name" => "Pizza Margherita",
        "price" => 8,
        "description" => "Pomodoro, mozzarella, basilico, semplice e deliziosa",
        "vegan" => false,
        "celiac" => false,
        "available" => true,
        "cover_image" => "images/cibo_4.jpg",
        'category_id' => 2,
        'restaurant_id' => 13,
    ],
    [
        "name" => "Pizza senza Glutine",
        "price" => 10,
        "description" => "Base senza glutine, ingredienti freschissimi",
        "vegan" => true,
        "celiac" => true,
        "available" => true,
        "cover_image" => "images/cibo_5.jpg",
        'category_id' => 2,
        'restaurant_id' => 13,
    ],
    [
        "name" => "Pizza Diavola",
        "price" => 8,
        "description" => "Piccante, saporita, con peperoncino e salame",
        "vegan" => false,
        "celiac" => false,
        "available" => true,
        "cover_image" => "images/cibo_10.jpg",
        'category_id' => 2,
        'restaurant_id' => 13,
    ],
    [
        "name" => "Pizza Boscaiola",
        "price" => 10,
        "description" => "Saporita, ricca di funghi e salsiccia",
        "vegan" => false,
        "celiac" => false,
        "available" => true,
        "cover_image" => "images/cibo_17.jpg",
        'category_id' => 2,
        'restaurant_id' => 13,
    ],
    [
        "name" => "Supplì",
        "price" => 11,
        "description" => "L'antipasto perfetto per una pizza",
        "vegan" => false,
        "celiac" => false,
        "available" => true,
        "cover_image" => "images/cibo_39.jpg",
        'category_id' => 2,
        'restaurant_id' => 13,
    ],

    // Big Bite

    [
        "name" => "Hamburger Americano",
        "price" => 16,
        "description" => "Doppia carne, formaggio, bacon, salsa segreta",
        "vegan" => false,
        "celiac" => false,
        "available" => true,
        "cover_image" => "images/cibo_8.jpg",
        'category_id' => 3,
        'restaurant_id' => 5,
    ],
    [
        "name" => "Hamburger",
        "price" => 8,
        "description" => "Gustoso, succulento, con carne di alta qualità",
        "vegan" => false,
        "celiac" => false,
        "available" => true,
        "cover_image" => "images/cibo_20.jpg",
        'category_id' => 3,
        'restaurant_id' => 5,
    ],
    [
        "name" => "Cheeseburger",
        "price" => 10,
        "description" => "Delizioso, con formaggio fuso cremosissimo",
        "vegan" => false,
        "celiac" => false,
        "available" => true,
        "cover_image" => "images/cibo_21.jpg",
        'category_id' => 3,
        'restaurant_id' => 5,
    ],
    [
        "name" => "Green Burger",
        "price" => 12,
        "description" => "Saporito, senza glutine, con hambuger di rapa rossa",
        "vegan" => true,
        "celiac" => true,
        "available" => true,
        "cover_image" => "images/cibo_22.jpg",
        'category_id' => 3,
        'restaurant_id' => 5,
    ],
    [
        "name" => "Chicken Burger",
        "price" => 12,
        "description" => "Succoso, croccantissimo, servito con Cesar salad",
        "vegan" => false,
        "celiac" => false,
        "available" => true,
        "cover_image" => "images/cibo_23.jpg",
        'category_id' => 3,
        'restaurant_id' => 5,
    ],
    [
        "name" => "Piccantissimo Burger",
        "price" => 14,
        "description" => "Esplosivo, ardente, con salsa Flame",
        "vegan" => false,
        "celiac" => false,
        "available" => true,
        "cover_image" => "images/cibo_24.jpg",
        'category_id' => 3,
        'restaurant_id' => 5,
    ],
    [
        "name" => "Patate fritte",
        "price" => 6,
        "description" => "Croccanti, dorate, irresistibili",
        "vegan" => true,
        "celiac" => true,
        "available" => true,
        "cover_image" => "images/cibo_34.jpg",
        'category_id' => 4,
        'restaurant_id' => 5,
    ],

    // Burger House
    [
        "name" => "Insalatona",
        "price" => 8,
        "description" => "Fresca, verde e variegata",
        "vegan" => true,
        "celiac" => true,
        "available" => true,
        "cover_image" => "images/cibo_35.jpg",
        'category_id' => 4,
        'restaurant_id' => 4,
    ],
    [
        "name" => "Grigliata Mista",
        "price" => 20,
        "description" => "Saporita e variegata, con carni e verdure alla brace",
        "vegan" => false,
        "celiac" => false,
        "available" => true,
        "cover_image" => "images/cibo_33.jpg",
        'category_id' => 3,
        'restaurant_id' => 4,
    ],
    [
        "name" => "Hamburger",
        "price" => 8,
        "description" => "Gustoso, succulento, con carne di alta qualità",
        "vegan" => false,
        "celiac" => false,
        "available" => true,
        "cover_image" => "images/cibo_20.jpg",
        'category_id' => 3,
        'restaurant_id' => 4,
    ],
    [
        "name" => "Cheeseburger",
        "price" => 10,
        "description" => "Delizioso, con formaggio fuso cremosissimo",
        "vegan" => false,
        "celiac" => false,
        "available" => true,
        "cover_image" => "images/cibo_21.jpg",
        'category_id' => 3,
        'restaurant_id' => 4,
    ],
    [
        "name" => "Cinnamon roll",
        "price" => 4,
        "description" => "Morbido, dolce, irresistibile",
        "vegan" => false,
        "celiac" => false,
        "available" => true,
        "cover_image" => "images/cibo_12.jpg",
        'category_id' => 5,
        'restaurant_id' => 4,
    ],
    [
        "name" => "Cheesecake",
        "price" => 6,
        "description" => "Cremosa, ricca e golosa",
        "vegan" => false,
        "celiac" => false,
        "available" => true,
        "cover_image" => "images/cibo_15.jpg",
        'category_id' => 5,
        'restaurant_id' => 4,
    ],

    // Fantasia Dolce

    [
        "name" => "Cinnamon roll",
        "price" => 4,
        "description" => "Morbido, dolce, irresistibile",
        "vegan" => false,
        "celiac" => false,
        "available" => true,
        "cover_image" => "images/cibo_12.jpg",
        'category_id' => 5,
        'restaurant_id' => 3,
    ],
    [
        "name" => "Muffin ai fiocchi d'Avena",
        "price" => 5,
        "description" => "Sani, gustosi, ricchi di fibre",
        "vegan" => true,
        "celiac" => true,
        "available" => true,
        "cover_image" => "images/cibo_13.jpg",
        'category_id' => 5,
        'restaurant_id' => 3,
    ],
    [
        "name" => "Brownies senza glutine",
        "price" => 5,
        "description" => "Deliziosi, leggeri, adatti a tutti",
        "vegan" => true,
        "celiac" => true,
        "available" => true,
        "cover_image" => "images/cibo_14.jpg",
        'category_id' => 5,
        'restaurant_id' => 3,
    ],
    [
        "name" => "Cheesecake",
        "price" => 6,
        "description" => "Cremosa, ricca e golosa",
        "vegan" => false,
        "celiac" => false,
        "available" => true,
        "cover_image" => "images/cibo_15.jpg",
        'category_id' => 5,
        'restaurant_id' => 3,
    ],
    [
        "name" => "Croissant",
        "price" => 2,
        "description" => "Fragranti, burrosi, squisiti",
        "vegan" => false,
        "celiac" => false,
        "available" => true,
        "cover_image" => "images/cibo_16.jpg",
        'category_id' => 5,
        'restaurant_id' => 3,
    ],
    [
        "name" => "Ciambelle",
        "price" => 5,
        "description" => "Farina, Latte, Zucchero, Olio di Semi",
        "vegan" => false,
        "celiac" => false,
        "available" => true,
        "cover_image" => "images/cibo_2.jpg",
        'category_id' => 5,
        'restaurant_id' => 3,
    ],

    // Gastronomia Elegante
    [
        "name" => "Tartare di Salmone",
        "price" => 15,
        "description" => "Fresco e aromatico, perfetto antipasto a base di Salmone Norevegese",
        "vegan" => false,
        "celiac" => true,
        "available" => true,
        "cover_image" => "images/cibo_6.jpg",
        'category_id' => 1,
        'restaurant_id' => 7,
    ],
    [
        "name" => "Tartare di Platessa",
        "price" => 15,
        "description" => "Tartare di Platessa selvatica, con scheda di pane alla curcuma e velluto di zucca",
        "vegan" => false,
        "celiac" => false,
        "available" => true,
        "cover_image" => "images/cibo_36.jpg",
        'category_id' => 3,
        'restaurant_id' => 7,
    ],
    [
        "name" => "Bucatini al nero di seppia",
        "price" => 15,
        "description" => "Bucatini al nero di seppia, con pomodorini e moscardini selvatici",
        "vegan" => false,
        "celiac" => false,
        "available" => true,
        "cover_image" => "images/cibo_37.jpg",
        'category_id' => 2,
        'restaurant_id' => 7,
    ],
    [
        "name" => "Spaghetti con le Vongole",
        "price" => 12,
        "description" => "Vongole fresche, aglio, prezzemolo e un tocco di peperoncino",
        "vegan" => false,
        "celiac" => false,
        "available" => true,
        "cover_image" => "images/cibo_11.jpg",
        'category_id' => 2,
        'restaurant_id' => 7,
    ],
    [
        "name" => "Cheesecake",
        "price" => 6,
        "description" => "Cremosa, ricca e golosa",
        "vegan" => false,
        "celiac" => false,
        "available" => true,
        "cover_image" => "images/cibo_15.jpg",
        'category_id' => 5,
        'restaurant_id' => 7,
    ],
    [
        "name" => "Croissant",
        "price" => 2,
        "description" => "Fragranti, burrosi, squisiti",
        "vegan" => false,
        "celiac" => false,
        "available" => true,
        "cover_image" => "images/cibo_16.jpg",
        'category_id' => 5,
        'restaurant_id' => 7,
    ],

    // Le Gourmet
    [
        "name" => "Caprese",
        "price" => 12,
        "description" => "Fettine di mozzarella di bufala e pomodorini verdi",
        "vegan" => false,
        "celiac" => true,
        "available" => true,
        "cover_image" => "images/cibo_38.jpg",
        'category_id' => 1,
        'restaurant_id' => 6,
    ],
    [
        "name" => "Ravioli Ricotta e Basilico",
        "price" => 12,
        "description" => "Delicati, saporiti, con ripieni cremoso e profumo di basilico",
        "vegan" => false,
        "celiac" => false,
        "available" => true,
        "cover_image" => "images/cibo_31.jpg",
        'category_id' => 2,
        'restaurant_id' => 6,
    ],
    [
        "name" => "Insalata di Quinoa",
        "price" => 12,
        "description" => "Quinoa, verdure fresche autoctone, dressing leggero",
        "vegan" => true,
        "celiac" => true,
        "available" => true,
        "cover_image" => "images/cibo_7.jpg",
        'category_id' => 4,
        'restaurant_id' => 6,
    ],
    [
        "name" => "Temaki",
        "price" => 6,
        "description" => "Ripieno di salmone freschissimo",
        "vegan" => false,
        "celiac" => false,
        "available" => true,
        "cover_image" => "images/cibo_28.jpg",
        'category_id' => 2,
        'restaurant_id' => 6,
    ],
    [
        "name" => "Sashimi",
        "price" => 8,
        "description" => "Fresco, prelibato, tagliato sottile",
        "vegan" => false,
        "celiac" => false,
        "available" => true,
        "cover_image" => "images/cibo_29.jpg",
        'category_id' => 2,
        'restaurant_id' => 6,
    ],

    // Sakura Sushi Bar

    [
        "name" => "Nigiri",
        "price" => 9,
        "description" => "Raffinati, freschi, prelibati",
        "vegan" => false,
        "celiac" => false,
        "available" => true,
        "cover_image" => "images/cibo_25.jpg",
        'category_id' => 2,
        'restaurant_id' => 8,
    ],
    [
        "name" => "Hosomaki",
        "price" => 6,
        "description" => "Gustosi, tradizionali, bocconcini di sushi avvolti",
        "vegan" => false,
        "celiac" => false,
        "available" => true,
        "cover_image" => "images/cibo_26.jpg",
        'category_id' => 2,
        'restaurant_id' => 8,
    ],
    [
        "name" => "Uramaki",
        "price" => 12,
        "description" => "Creativi, avvolgenti, con ripieni assortiti",
        "vegan" => false,
        "celiac" => false,
        "available" => true,
        "cover_image" => "images/cibo_27.jpg",
        'category_id' => 2,
        'restaurant_id' => 8,
    ],
    [
        "name" => "Temaki",
        "price" => 6,
        "description" => "Ripieno di salmone freschissimo",
        "vegan" => false,
        "celiac" => false,
        "available" => true,
        "cover_image" => "images/cibo_28.jpg",
        'category_id' => 2,
        'restaurant_id' => 8,
    ],
    [
        "name" => "Sashimi",
        "price" => 8,
        "description" => "Fresco, prelibato, tagliato sottile",
        "vegan" => false,
        "celiac" => false,
        "available" => true,
        "cover_image" => "images/cibo_29.jpg",
        'category_id' => 2,
        'restaurant_id' => 8,
    ],
    [
        "name" => "Onigiri",
        "price" => 4,
        "description" => "Deliziosi, con riso integrale e ripieni di alghe giapponesi",
        "vegan" => true,
        "celiac" => true,
        "available" => true,
        "cover_image" => "images/cibo_30.jpg",
        'category_id' => 2,
        'restaurant_id' => 8,
    ],
    [
        "name" => "Insalata di Quinoa",
        "price" => 12,
        "description" => "Quinoa, verdure fresche autoctone, dressing leggero",
        "vegan" => true,
        "celiac" => true,
        "available" => true,
        "cover_image" => "images/cibo_7.jpg",
        'category_id' => 4,
        'restaurant_id' => 8,
    ],

    // Dragon Wok

    [
        "name" => "Riso cantonese",
        "price" => 7,
        "description" => "Deliziosa combinazione di riso saltato con numerosi aromi",
        "vegan" => true,
        "celiac" => true,
        "available" => true,
        "cover_image" => "images/cibo_40.jpg",
        'category_id' => 2,
        'restaurant_id' => 9,
    ],
    [
        "name" => "Involtini primavera",
        "price" => 5,
        "description" => "Croccanti involuti fritti con verdure",
        "vegan" => true,
        "celiac" => true,
        "available" => true,
        "cover_image" => "images/cibo_41.jpg",
        'category_id' => 1,
        'restaurant_id' => 9,
    ],
    [
        "name" => "Zuppa Wonton",
        "price" => 8,
        "description" => "Brodo caldo e avvolgente arricchito di aromi",
        "vegan" => true,
        "celiac" => false,
        "available" => true,
        "cover_image" => "images/cibo_42.jpg",
        'category_id' => 1,
        'restaurant_id' => 9,
    ],
    [
        "name" => "Ravioli",
        "price" => 9,
        "description" => "Delicati e gustosi ravioli ripieni di carne e aromi",
        "vegan" => false,
        "celiac" => false,
        "available" => true,
        "cover_image" => "images/cibo_43.jpg",
        'category_id' => 2,
        'restaurant_id' => 9,
    ],
    [
        "name" => "Tofù in agrodolce",
        "price" => 6,
        "description" => "Cubetti di tofù dorati, cotti in salsa agrodolce",
        "vegan" => true,
        "celiac" => true,
        "available" => true,
        "cover_image" => "images/cibo_44.jpg",
        'category_id' => 3,
        'restaurant_id' => 9,
    ],
    [
        "name" => "Maiale in agrodolce",
        "price" => 10,
        "description" => "Succulento maialino cotto in salsa agrodolce",
        "vegan" => false,
        "celiac" => false,
        "available" => true,
        "cover_image" => "images/cibo_45.jpg",
        'category_id' => 3,
        'restaurant_id' => 9,
    ],

    // Golden Panda

    [
        "name" => "Nigiri",
        "price" => 9,
        "description" => "Raffinati, freschi, prelibati",
        "vegan" => false,
        "celiac" => false,
        "available" => true,
        "cover_image" => "images/cibo_25.jpg",
        'category_id' => 2,
        'restaurant_id' => 10,
    ],
    [
        "name" => "Hosomaki",
        "price" => 6,
        "description" => "Gustosi, tradizionali, bocconcini di sushi avvolti",
        "vegan" => false,
        "celiac" => false,
        "available" => true,
        "cover_image" => "images/cibo_26.jpg",
        'category_id' => 2,
        'restaurant_id' => 10,
    ],
    [
        "name" => "Uramaki",
        "price" => 12,
        "description" => "Creativi, avvolgenti, con ripieni assortiti",
        "vegan" => false,
        "celiac" => false,
        "available" => true,
        "cover_image" => "images/cibo_27.jpg",
        'category_id' => 2,
        'restaurant_id' => 10,
    ],
    [
        "name" => "Temaki",
        "price" => 6,
        "description" => "Ripieno di salmone freschissimo",
        "vegan" => false,
        "celiac" => false,
        "available" => true,
        "cover_image" => "images/cibo_28.jpg",
        'category_id' => 2,
        'restaurant_id' => 10,
    ],
    [
        "name" => "Sashimi",
        "price" => 8,
        "description" => "Fresco, prelibato, tagliato sottile",
        "vegan" => false,
        "celiac" => false,
        "available" => true,
        "cover_image" => "images/cibo_29.jpg",
        'category_id' => 2,
        'restaurant_id' => 10,
    ],
    [
        "name" => "Onigiri",
        "price" => 4,
        "description" => "Deliziosi, con riso integrale e ripieni di alghe giapponesi",
        "vegan" => true,
        "celiac" => true,
        "available" => true,
        "cover_image" => "images/cibo_30.jpg",
        'category_id' => 2,
        'restaurant_id' => 10,
    ],
    [
        "name" => "Insalata di Quinoa",
        "price" => 12,
        "description" => "Quinoa, verdure fresche autoctone, dressing leggero",
        "vegan" => true,
        "celiac" => true,
        "available" => true,
        "cover_image" => "images/cibo_7.jpg",
        'category_id' => 4,
        'restaurant_id' => 10,
    ],
    [
        "name" => "Riso cantonese",
        "price" => 7,
        "description" => "Deliziosa combinazione di riso saltato con numerosi aromi",
        "vegan" => true,
        "celiac" => true,
        "available" => true,
        "cover_image" => "images/cibo_40.jpg",
        'category_id' => 2,
        'restaurant_id' => 10,
    ],
    [
        "name" => "Involtini primavera",
        "price" => 5,
        "description" => "Croccanti involuti fritti con verdure",
        "vegan" => true,
        "celiac" => true,
        "available" => true,
        "cover_image" => "images/cibo_41.jpg",
        'category_id' => 1,
        'restaurant_id' => 10,
    ],
    [
        "name" => "Zuppa Wonton",
        "price" => 8,
        "description" => "Brodo caldo e avvolgente arricchito di aromi",
        "vegan" => true,
        "celiac" => false,
        "available" => true,
        "cover_image" => "images/cibo_42.jpg",
        'category_id' => 1,
        'restaurant_id' => 10,
    ],
    [
        "name" => "Ravioli",
        "price" => 9,
        "description" => "Delicati e gustosi ravioli ripieni di carne e aromi",
        "vegan" => false,
        "celiac" => false,
        "available" => true,
        "cover_image" => "images/cibo_43.jpg",
        'category_id' => 2,
        'restaurant_id' => 10,
    ],
    [
        "name" => "Tofù in agrodolce",
        "price" => 6,
        "description" => "Cubetti di tofù dorati, cotti in salsa agrodolce",
        "vegan" => true,
        "celiac" => true,
        "available" => true,
        "cover_image" => "images/cibo_44.jpg",
        'category_id' => 3,
        'restaurant_id' => 10,
    ],
    [
        "name" => "Maiale in agrodolce",
        "price" => 10,
        "description" => "Succulento maialino cotto in salsa agrodolce",
        "vegan" => false,
        "celiac" => false,
        "available" => true,
        "cover_image" => "images/cibo_45.jpg",
        'category_id' => 3,
        'restaurant_id' => 10,
    ],

    // Great Wall

    [
        "name" => "Patate fritte",
        "price" => 6,
        "description" => "Croccanti, dorate, irresistibili",
        "vegan" => true,
        "celiac" => true,
        "available" => true,
        "cover_image" => "images/cibo_34.jpg",
        'category_id' => 4,
        'restaurant_id' => 11,
    ],
    [
        "name" => "Insalatona",
        "price" => 8,
        "description" => "Fresca, verde e variegata",
        "vegan" => true,
        "celiac" => true,
        "available" => true,
        "cover_image" => "images/cibo_35.jpg",
        'category_id' => 4,
        'restaurant_id' => 11,
    ],
    [
        "name" => "Nigiri",
        "price" => 9,
        "description" => "Raffinati, freschi, prelibati",
        "vegan" => false,
        "celiac" => false,
        "available" => true,
        "cover_image" => "images/cibo_25.jpg",
        'category_id' => 2,
        'restaurant_id' => 11,
    ],
    [
        "name" => "Hosomaki",
        "price" => 6,
        "description" => "Gustosi, tradizionali, bocconcini di sushi avvolti",
        "vegan" => false,
        "celiac" => false,
        "available" => true,
        "cover_image" => "images/cibo_26.jpg",
        'category_id' => 2,
        'restaurant_id' => 11,
    ],
    [
        "name" => "Uramaki",
        "price" => 12,
        "description" => "Creativi, avvolgenti, con ripieni assortiti",
        "vegan" => false,
        "celiac" => false,
        "available" => true,
        "cover_image" => "images/cibo_27.jpg",
        'category_id' => 2,
        'restaurant_id' => 11,
    ],
    [
        "name" => "Temaki",
        "price" => 6,
        "description" => "Ripieno di salmone freschissimo",
        "vegan" => false,
        "celiac" => false,
        "available" => true,
        "cover_image" => "images/cibo_28.jpg",
        'category_id' => 2,
        'restaurant_id' => 11,
    ],
    [
        "name" => "Sashimi",
        "price" => 8,
        "description" => "Fresco, prelibato, tagliato sottile",
        "vegan" => false,
        "celiac" => false,
        "available" => true,
        "cover_image" => "images/cibo_29.jpg",
        'category_id' => 2,
        'restaurant_id' => 11,
    ],
    [
        "name" => "Onigiri",
        "price" => 4,
        "description" => "Deliziosi, con riso integrale e ripieni di alghe giapponesi",
        "vegan" => true,
        "celiac" => true,
        "available" => true,
        "cover_image" => "images/cibo_30.jpg",
        'category_id' => 2,
        'restaurant_id' => 11,
    ],
    [
        "name" => "Insalata di Quinoa",
        "price" => 12,
        "description" => "Quinoa, verdure fresche autoctone, dressing leggero",
        "vegan" => true,
        "celiac" => true,
        "available" => true,
        "cover_image" => "images/cibo_7.jpg",
        'category_id' => 4,
        'restaurant_id' => 11,
    ],
    [
        "name" => "Riso cantonese",
        "price" => 7,
        "description" => "Deliziosa combinazione di riso saltato con numerosi aromi",
        "vegan" => true,
        "celiac" => true,
        "available" => true,
        "cover_image" => "images/cibo_40.jpg",
        'category_id' => 2,
        'restaurant_id' => 11,
    ],
    [
        "name" => "Involtini primavera",
        "price" => 5,
        "description" => "Croccanti involuti fritti con verdure",
        "vegan" => true,
        "celiac" => true,
        "available" => true,
        "cover_image" => "images/cibo_41.jpg",
        'category_id' => 1,
        'restaurant_id' => 11,
    ],
    [
        "name" => "Zuppa Wonton",
        "price" => 8,
        "description" => "Brodo caldo e avvolgente arricchito di aromi",
        "vegan" => true,
        "celiac" => false,
        "available" => true,
        "cover_image" => "images/cibo_42.jpg",
        'category_id' => 1,
        'restaurant_id' => 11,
    ],
    [
        "name" => "Ravioli",
        "price" => 9,
        "description" => "Delicati e gustosi ravioli ripieni di carne e aromi",
        "vegan" => false,
        "celiac" => false,
        "available" => true,
        "cover_image" => "images/cibo_43.jpg",
        'category_id' => 2,
        'restaurant_id' => 11,
    ],
    [
        "name" => "Tofù in agrodolce",
        "price" => 6,
        "description" => "Cubetti di tofù dorati, cotti in salsa agrodolce",
        "vegan" => true,
        "celiac" => true,
        "available" => true,
        "cover_image" => "images/cibo_44.jpg",
        'category_id' => 3,
        'restaurant_id' => 11,
    ],
    [
        "name" => "Maiale in agrodolce",
        "price" => 10,
        "description" => "Succulento maialino cotto in salsa agrodolce",
        "vegan" => false,
        "celiac" => false,
        "available" => true,
        "cover_image" => "images/cibo_45.jpg",
        'category_id' => 3,
        'restaurant_id' => 11,
    ],
    [
        "name" => "Tartare di Salmone",
        "price" => 15,
        "description" => "Fresco e aromatico, perfetto antipasto a base di Salmone Norevegese",
        "vegan" => false,
        "celiac" => true,
        "available" => true,
        "cover_image" => "images/cibo_6.jpg",
        'category_id' => 1,
        'restaurant_id' => 11,
    ],
    [
        "name" => "Insalata di Quinoa",
        "price" => 12,
        "description" => "Quinoa, verdure fresche autoctone, dressing leggero",
        "vegan" => true,
        "celiac" => true,
        "available" => true,
        "cover_image" => "images/cibo_7.jpg",
        'category_id' => 4,
        'restaurant_id' => 11,
    ],
    [
        "name" => "Tartare di Platessa",
        "price" => 15,
        "description" => "Tartare di Platessa selvatica, con scheda di pane alla curcuma e velluto di zucca",
        "vegan" => false,
        "celiac" => false,
        "available" => true,
        "cover_image" => "images/cibo_36.jpg",
        'category_id' => 3,
        'restaurant_id' => 11,
    ],
    [
        "name" => "Bucatini al nero di seppia",
        "price" => 15,
        "description" => "Bucatini al nero di seppia, con pomodorini e moscardini selvatici",
        "vegan" => false,
        "celiac" => false,
        "available" => true,
        "cover_image" => "images/cibo_37.jpg",
        'category_id' => 2,
        'restaurant_id' => 11,
    ],
    [
        "name" => "Caprese",
        "price" => 12,
        "description" => "Fettine di mozzarella di bufala e pomodorini verdi",
        "vegan" => false,
        "celiac" => true,
        "available" => true,
        "cover_image" => "images/cibo_38.jpg",
        'category_id' => 1,
        'restaurant_id' => 11,
    ],

    // Fast & Tasty
    [
        "name" => "Pizza Margherita",
        "price" => 8,
        "description" => "Pomodoro, mozzarella, basilico, semplice e deliziosa",
        "vegan" => false,
        "celiac" => false,
        "available" => true,
        "cover_image" => "images/cibo_4.jpg",
        'category_id' => 2,
        'restaurant_id' => 15,
    ],
    [
        "name" => "Pizza Diavola",
        "price" => 8,
        "description" => "Piccante, saporita, con peperoncino e salame",
        "vegan" => false,
        "celiac" => false,
        "available" => true,
        "cover_image" => "images/cibo_10.jpg",
        'category_id' => 2,
        'restaurant_id' => 15,
    ],
    [
        "name" => "Pizza Boscaiola",
        "price" => 10,
        "description" => "Saporita, ricca di funghi e salsiccia",
        "vegan" => false,
        "celiac" => false,
        "available" => true,
        "cover_image" => "images/cibo_17.jpg",
        'category_id' => 2,
        'restaurant_id' => 15,
    ],
    [
        "name" => "Pizza Quattro Stagioni",
        "price" => 11,
        "description" => "Con prosciutto, olive, carciofi e funghi",
        "vegan" => false,
        "celiac" => false,
        "available" => true,
        "cover_image" => "images/cibo_19.jpg",
        'category_id' => 2,
        'restaurant_id' => 15,
    ],
    [
        "name" => "Hamburger Americano",
        "price" => 16,
        "description" => "Doppia carne, formaggio, bacon, salsa segreta",
        "vegan" => false,
        "celiac" => false,
        "available" => true,
        "cover_image" => "images/cibo_8.jpg",
        'category_id' => 3,
        'restaurant_id' => 15,
    ],
    [
        "name" => "Hamburger",
        "price" => 8,
        "description" => "Gustoso, succulento, con carne di alta qualità",
        "vegan" => false,
        "celiac" => false,
        "available" => true,
        "cover_image" => "images/cibo_20.jpg",
        'category_id' => 3,
        'restaurant_id' => 15,
    ],
    [
        "name" => "Cheeseburger",
        "price" => 10,
        "description" => "Delizioso, con formaggio fuso cremosissimo",
        "vegan" => false,
        "celiac" => false,
        "available" => true,
        "cover_image" => "images/cibo_21.jpg",
        'category_id' => 3,
        'restaurant_id' => 15,
    ],
    [
        "name" => "Chicken Burger",
        "price" => 12,
        "description" => "Succoso, croccantissimo, servito con Cesar salad",
        "vegan" => false,
        "celiac" => false,
        "available" => true,
        "cover_image" => "images/cibo_23.jpg",
        'category_id' => 3,
        'restaurant_id' => 15,
    ],
    [
        "name" => "Piccantissimo Burger",
        "price" => 14,
        "description" => "Esplosivo, ardente, con salsa Flame",
        "vegan" => false,
        "celiac" => false,
        "available" => true,
        "cover_image" => "images/cibo_24.jpg",
        'category_id' => 3,
        'restaurant_id' => 15,
    ],
    [
        "name" => "Patate fritte",
        "price" => 6,
        "description" => "Croccanti, dorate, irresistibili",
        "vegan" => true,
        "celiac" => true,
        "available" => true,
        "cover_image" => "images/cibo_34.jpg",
        'category_id' => 4,
        'restaurant_id' => 15,
    ],

    // Quick Bites

    [
        "name" => "Muffin ai fiocchi d'Avena",
        "price" => 5,
        "description" => "Sani, gustosi, ricchi di fibre",
        "vegan" => true,
        "celiac" => true,
        "available" => true,
        "cover_image" => "images/cibo_13.jpg",
        'category_id' => 5,
        'restaurant_id' => 14,
    ],
    [
        "name" => "Brownies senza glutine",
        "price" => 5,
        "description" => "Deliziosi, leggeri, adatti a tutti",
        "vegan" => true,
        "celiac" => true,
        "available" => true,
        "cover_image" => "images/cibo_14.jpg",
        'category_id' => 5,
        'restaurant_id' => 14,
    ],
    [
        "name" => "Green Burger",
        "price" => 12,
        "description" => "Saporito, senza glutine, con hambuger di rapa rossa",
        "vegan" => true,
        "celiac" => true,
        "available" => true,
        "cover_image" => "images/cibo_22.jpg",
        'category_id' => 3,
        'restaurant_id' => 14,
    ],
    [
        "name" => "Insalata di Quinoa",
        "price" => 12,
        "description" => "Quinoa, verdure fresche autoctone, dressing leggero",
        "vegan" => true,
        "celiac" => true,
        "available" => true,
        "cover_image" => "images/cibo_7.jpg",
        'category_id' => 4,
        'restaurant_id' => 14,
    ],
    [
        "name" => "Hamburger di Tofù",
        "price" => 9,
        "description" => "Hamburger di tofù con verdure, senza glutine",
        "vegan" => true,
        "celiac" => true,
        "available" => true,
        "cover_image" => "images/cibo_46.jpg",
        'category_id' => 3,
        'restaurant_id' => 14,
    ],
    [
        "name" => "Patate fritte",
        "price" => 6,
        "description" => "Croccanti, dorate, irresistibili",
        "vegan" => true,
        "celiac" => true,
        "available" => true,
        "cover_image" => "images/cibo_34.jpg",
        'category_id' => 4,
        'restaurant_id' => 14,
    ],

    // Speedy Eats

    [
        "name" => "Hamburger di Tofù",
        "price" => 9,
        "description" => "Hamburger di tofù con verdure, senza glutine",
        "vegan" => true,
        "celiac" => true,
        "available" => true,
        "cover_image" => "images/cibo_46.jpg",
        'category_id' => 3,
        'restaurant_id' => 16,
    ],
    [
        "name" => "Cinnamon roll",
        "price" => 4,
        "description" => "Morbido, dolce, irresistibile",
        "vegan" => false,
        "celiac" => false,
        "available" => true,
        "cover_image" => "images/cibo_12.jpg",
        'category_id' => 5,
        'restaurant_id' => 16,
    ],
    [
        "name" => "Muffin ai fiocchi d'Avena",
        "price" => 5,
        "description" => "Sani, gustosi, ricchi di fibre",
        "vegan" => true,
        "celiac" => true,
        "available" => true,
        "cover_image" => "images/cibo_13.jpg",
        'category_id' => 5,
        'restaurant_id' => 16,
    ],
    [
        "name" => "Brownies senza glutine",
        "price" => 5,
        "description" => "Deliziosi, leggeri, adatti a tutti",
        "vegan" => true,
        "celiac" => true,
        "available" => true,
        "cover_image" => "images/cibo_14.jpg",
        'category_id' => 5,
        'restaurant_id' => 16,
    ],
    [
        "name" => "Cheesecake",
        "price" => 6,
        "description" => "Cremosa, ricca e golosa",
        "vegan" => false,
        "celiac" => false,
        "available" => true,
        "cover_image" => "images/cibo_15.jpg",
        'category_id' => 5,
        'restaurant_id' => 16,
    ],
    [
        "name" => "Croissant",
        "price" => 2,
        "description" => "Fragranti, burrosi, squisiti",
        "vegan" => false,
        "celiac" => false,
        "available" => true,
        "cover_image" => "images/cibo_16.jpg",
        'category_id' => 5,
        'restaurant_id' => 16,
    ],
    [
        "name" => "Ciambelle",
        "price" => 5,
        "description" => "Farina, Latte, Zucchero, Olio di Semi",
        "vegan" => false,
        "celiac" => false,
        "available" => true,
        "cover_image" => "images/cibo_2.jpg",
        'category_id' => 5,
        'restaurant_id' => 16,
    ],
    [
        "name" => "Hamburger Americano",
        "price" => 16,
        "description" => "Doppia carne, formaggio, bacon, salsa segreta",
        "vegan" => false,
        "celiac" => false,
        "available" => true,
        "cover_image" => "images/cibo_8.jpg",
        'category_id' => 3,
        'restaurant_id' => 16,
    ],
    [
        "name" => "Hamburger",
        "price" => 8,
        "description" => "Gustoso, succulento, con carne di alta qualità",
        "vegan" => false,
        "celiac" => false,
        "available" => true,
        "cover_image" => "images/cibo_20.jpg",
        'category_id' => 3,
        'restaurant_id' => 16,
    ],
    [
        "name" => "Cheeseburger",
        "price" => 10,
        "description" => "Delizioso, con formaggio fuso cremosissimo",
        "vegan" => false,
        "celiac" => false,
        "available" => true,
        "cover_image" => "images/cibo_21.jpg",
        'category_id' => 3,
        'restaurant_id' => 16,
    ],
    [
        "name" => "Green Burger",
        "price" => 12,
        "description" => "Saporito, senza glutine, con hambuger di rapa rossa",
        "vegan" => true,
        "celiac" => true,
        "available" => true,
        "cover_image" => "images/cibo_22.jpg",
        'category_id' => 3,
        'restaurant_id' => 16,
    ],
    [
        "name" => "Chicken Burger",
        "price" => 12,
        "description" => "Succoso, croccantissimo, servito con Cesar salad",
        "vegan" => false,
        "celiac" => false,
        "available" => true,
        "cover_image" => "images/cibo_23.jpg",
        'category_id' => 3,
        'restaurant_id' => 16,
    ],
    [
        "name" => "Piccantissimo Burger",
        "price" => 14,
        "description" => "Esplosivo, ardente, con salsa Flame",
        "vegan" => false,
        "celiac" => false,
        "available" => true,
        "cover_image" => "images/cibo_24.jpg",
        'category_id' => 3,
        'restaurant_id' => 16,
    ],
    [
        "name" => "Patate fritte",
        "price" => 6,
        "description" => "Croccanti, dorate, irresistibili",
        "vegan" => true,
        "celiac" => true,
        "available" => true,
        "cover_image" => "images/cibo_34.jpg",
        'category_id' => 4,
        'restaurant_id' => 16,
    ],
];

   // PASTICCERIA

    // [
    //     "name" => "Cinnamon roll",
    //     "price" => 4,
    //     "description" => "Morbido, dolce, irresistibile",
    //     "vegan" => false,
    //     "celiac" => false,
    //     "available" => true,
    //     "cover_image" => "images/cibo_12.jpg",
    //     'category_id' => 5,
    //     'restaurant_id' => 2,
    // ],
    // [
    //     "name" => "Muffin ai fiocchi d'Avena",
    //     "price" => 5,
    //     "description" => "Sani, gustosi, ricchi di fibre",
    //     "vegan" => true,
    //     "celiac" => true,
    //     "available" => true,
    //     "cover_image" => "images/cibo_13.jpg",
    //     'category_id' => 5,
    //     'restaurant_id' => 2,
    // ],
    // [
    //     "name" => "Brownies senza glutine",
    //     "price" => 5,
    //     "description" => "Deliziosi, leggeri, adatti a tutti",
    //     "vegan" => true,
    //     "celiac" => true,
    //     "available" => true,
    //     "cover_image" => "images/cibo_14.jpg",
    //     'category_id' => 5,
    //     'restaurant_id' => 2,
    // ],
    // [
    //     "name" => "Cheesecake",
    //     "price" => 6,
    //     "description" => "Cremosa, ricca e golosa",
    //     "vegan" => false,
    //     "celiac" => false,
    //     "available" => true,
    //     "cover_image" => "images/cibo_15.jpg",
    //     'category_id' => 5,
    //     'restaurant_id' => 2,
    // ],
    // [
    //     "name" => "Croissant",
    //     "price" => 2,
    //     "description" => "Fragranti, burrosi, squisiti",
    //     "vegan" => false,
    //     "celiac" => false,
    //     "available" => true,
    //     "cover_image" => "images/cibo_16.jpg",
    //     'category_id' => 5,
    //     'restaurant_id' => 2,
    // ],
    // [
    //     "name" => "Ciambelle",
    //     "price" => 5,
    //     "description" => "Farina, Latte, Zucchero, Olio di Semi",
    //     "vegan" => false,
    //     "celiac" => false,
    //     "available" => true,
    //     "cover_image" => "images/cibo_2.jpg",
    //     'category_id' => 5,
    //     'restaurant_id' => 2,
    // ],

    // HAMBURGER

    // [
    //     "name" => "Hamburger Americano",
    //     "price" => 16,
    //     "description" => "Doppia carne, formaggio, bacon, salsa segreta",
    //     "vegan" => false,
    //     "celiac" => false,
    //     "available" => true,
    //     "cover_image" => "images/cibo_8.jpg",
    //     'category_id' => 3,
    //     'restaurant_id' => 5,
    // ],
    // [
    //     "name" => "Hamburger",
    //     "price" => 8,
    //     "description" => "Gustoso, succulento, con carne di alta qualità",
    //     "vegan" => false,
    //     "celiac" => false,
    //     "available" => true,
    //     "cover_image" => "images/cibo_20.jpg",
    //     'category_id' => 3,
    //     'restaurant_id' => 5,
    // ],
    // [
    //     "name" => "Cheeseburger",
    //     "price" => 10,
    //     "description" => "Delizioso, con formaggio fuso cremosissimo",
    //     "vegan" => false,
    //     "celiac" => false,
    //     "available" => true,
    //     "cover_image" => "images/cibo_21.jpg",
    //     'category_id' => 3,
    //     'restaurant_id' => 5,
    // ],
    // [
    //     "name" => "Green Burger",
    //     "price" => 12,
    //     "description" => "Saporito, senza glutine, con hambuger di rapa rossa",
    //     "vegan" => true,
    //     "celiac" => true,
    //     "available" => true,
    //     "cover_image" => "images/cibo_22.jpg",
    //     'category_id' => 3,
    //     'restaurant_id' => 5,
    // ],
    // [
    //     "name" => "Chicken Burger",
    //     "price" => 12,
    //     "description" => "Succoso, croccantissimo, servito con Cesar salad",
    //     "vegan" => false,
    //     "celiac" => false,
    //     "available" => true,
    //     "cover_image" => "images/cibo_23.jpg",
    //     'category_id' => 3,
    //     'restaurant_id' => 5,
    // ],
    // [
    //     "name" => "Piccantissimo Burger",
    //     "price" => 14,
    //     "description" => "Esplosivo, ardente, con salsa Flame",
    //     "vegan" => false,
    //     "celiac" => false,
    //     "available" => true,
    //     "cover_image" => "images/cibo_24.jpg",
    //     'category_id' => 3,
    //     'restaurant_id' => 5,
    // ],
    // [
    //     "name" => "Patate fritte",
    //     "price" => 6,
    //     "description" => "Croccanti, dorate, irresistibili",
    //     "vegan" => true,
    //     "celiac" => true,
    //     "available" => true,
    //     "cover_image" => "images/cibo_34.jpg",
    //     'category_id' => 4,
    //     'restaurant_id' => 1,
    // ],

    // GOURMET

    // [
    //     "name" => "Ravioli Ricotta e Basilico",
    //     "price" => 12,
    //     "description" => "Delicati, saporiti, con ripieni cremoso e profumo di basilico",
    //     "vegan" => false,
    //     "celiac" => false,
    //     "available" => true,
    //     "cover_image" => "images/cibo_31.jpg",
    //     'category_id' => 2,
    //     'restaurant_id' => 2,
    // ],
    // [
    //     "name" => "Tartare di Salmone",
    //     "price" => 15,
    //     "description" => "Fresco e aromatico, perfetto antipasto a base di Salmone Norevegese",
    //     "vegan" => false,
    //     "celiac" => true,
    //     "available" => true,
    //     "cover_image" => "images/cibo_6.jpg",
    //     'category_id' => 1,
    //     'restaurant_id' => 3,
    // ],
    // [
    //     "name" => "Insalata di Quinoa",
    //     "price" => 12,
    //     "description" => "Quinoa, verdure fresche autoctone, dressing leggero",
    //     "vegan" => true,
    //     "celiac" => true,
    //     "available" => true,
    //     "cover_image" => "images/cibo_7.jpg",
    //     'category_id' => 4,
    //     'restaurant_id' => 1,
    // ],
    // [
    //     "name" => "Tartare di Platessa",
    //     "price" => 15,
    //     "description" => "Tartare di Platessa selvatica, con scheda di pane alla curcuma e velluto di zucca",
    //     "vegan" => false,
    //     "celiac" => false,
    //     "available" => true,
    //     "cover_image" => "images/cibo_36.jpg",
    //     'category_id' => 3,
    //     'restaurant_id' => 7,
    // ],
    // [
    //     "name" => "Bucatini al nero di seppia",
    //     "price" => 15,
    //     "description" => "Bucatini al nero di seppia, con pomodorini e moscardini selvatici",
    //     "vegan" => false,
    //     "celiac" => false,
    //     "available" => true,
    //     "cover_image" => "images/cibo_37.jpg",
    //     'category_id' => 2,
    //     'restaurant_id' => 1,
    // ],
    // [
    //     "name" => "Caprese",
    //     "price" => 12,
    //     "description" => "Fettine di mozzarella di bufala e pomodorini verdi",
    //     "vegan" => false,
    //     "celiac" => true,
    //     "available" => true,
    //     "cover_image" => "images/cibo_38.jpg",
    //     'category_id' => 1,
    //     'restaurant_id' => 1,
    // ],

    // GIAPPONESE

    // [
    //     "name" => "Nigiri",
    //     "price" => 9,
    //     "description" => "Raffinati, freschi, prelibati",
    //     "vegan" => false,
    //     "celiac" => false,
    //     "available" => true,
    //     "cover_image" => "images/cibo_25.jpg",
    //     'category_id' => 2,
    //     'restaurant_id' => 4,
    // ],
    // [
    //     "name" => "Hosomaki",
    //     "price" => 6,
    //     "description" => "Gustosi, tradizionali, bocconcini di sushi avvolti",
    //     "vegan" => false,
    //     "celiac" => false,
    //     "available" => true,
    //     "cover_image" => "images/cibo_26.jpg",
    //     'category_id' => 2,
    //     'restaurant_id' => 4,
    // ],
    // [
    //     "name" => "Uramaki",
    //     "price" => 12,
    //     "description" => "Creativi, avvolgenti, con ripieni assortiti",
    //     "vegan" => false,
    //     "celiac" => false,
    //     "available" => true,
    //     "cover_image" => "images/cibo_27.jpg",
    //     'category_id' => 2,
    //     'restaurant_id' => 4,
    // ],
    // [
    //     "name" => "Temaki",
    //     "price" => 6,
    //     "description" => "Ripieno di salmone freschissimo",
    //     "vegan" => false,
    //     "celiac" => false,
    //     "available" => true,
    //     "cover_image" => "images/cibo_28.jpg",
    //     'category_id' => 2,
    //     'restaurant_id' => 4,
    // ],
    // [
    //     "name" => "Sashimi",
    //     "price" => 8,
    //     "description" => "Fresco, prelibato, tagliato sottile",
    //     "vegan" => false,
    //     "celiac" => false,
    //     "available" => true,
    //     "cover_image" => "images/cibo_29.jpg",
    //     'category_id' => 2,
    //     'restaurant_id' => 4,
    // ],
    // [
    //     "name" => "Onigiri",
    //     "price" => 4,
    //     "description" => "Deliziosi, con riso integrale e ripieni di alghe giapponesi",
    //     "vegan" => true,
    //     "celiac" => true,
    //     "available" => true,
    //     "cover_image" => "images/cibo_30.jpg",
    //     'category_id' => 2,
    //     'restaurant_id' => 4,
    // ],
    // [
    //     "name" => "Insalata di Quinoa",
    //     "price" => 12,
    //     "description" => "Quinoa, verdure fresche autoctone, dressing leggero",
    //     "vegan" => true,
    //     "celiac" => true,
    //     "available" => true,
    //     "cover_image" => "images/cibo_7.jpg",
    //     'category_id' => 4,
    //     'restaurant_id' => 1,
    // ],

    // CINESE

    // [
    //     "name" => "Riso cantonese",
    //     "price" => 7,
    //     "description" => "Deliziosa combinazione di riso saltato con numerosi aromi",
    //     "vegan" => true,
    //     "celiac" => true,
    //     "available" => true,
    //     "cover_image" => "images/cibo_40.jpg",
    //     'category_id' => 2,
    //     'restaurant_id' => 2,
    // ],
    // [
    //     "name" => "Involtini primavera",
    //     "price" => 5,
    //     "description" => "Croccanti involuti fritti con verdure",
    //     "vegan" => true,
    //     "celiac" => true,
    //     "available" => true,
    //     "cover_image" => "images/cibo_41.jpg",
    //     'category_id' => 1,
    //     'restaurant_id' => 2,
    // ],
    // [
    //     "name" => "Zuppa Wonton",
    //     "price" => 8,
    //     "description" => "Brodo caldo e avvolgente arricchito di aromi",
    //     "vegan" => true,
    //     "celiac" => false,
    //     "available" => true,
    //     "cover_image" => "images/cibo_42.jpg",
    //     'category_id' => 1,
    //     'restaurant_id' => 2,
    // ],
    // [
    //     "name" => "Ravioli",
    //     "price" => 9,
    //     "description" => "Delicati e gustosi ravioli ripieni di carne e aromi",
    //     "vegan" => false,
    //     "celiac" => false,
    //     "available" => true,
    //     "cover_image" => "images/cibo_43.jpg",
    //     'category_id' => 2,
    //     'restaurant_id' => 2,
    // ],
    // [
    //     "name" => "Tofù in agrodolce",
    //     "price" => 6,
    //     "description" => "Cubetti di tofù dorati, cotti in salsa agrodolce",
    //     "vegan" => true,
    //     "celiac" => true,
    //     "available" => true,
    //     "cover_image" => "images/cibo_44.jpg",
    //     'category_id' => 3,
    //     'restaurant_id' => 2,
    // ],
    // [
    //     "name" => "Maiale in agrodolce",
    //     "price" => 10,
    //     "description" => "Succulento maialino cotto in salsa agrodolce",
    //     "vegan" => false,
    //     "celiac" => false,
    //     "available" => true,
    //     "cover_image" => "images/cibo_45.jpg",
    //     'category_id' => 3,
    //     'restaurant_id' => 2,
    // ],

    // TRATTORIA

    // [
    //     "name" => "Spaghetti di zucchine",
    //     "price" => 10,
    //     "description" => "Zucchine, pomodoro fresco, basilico, senza glutine",
    //     "vegan" => true,
    //     "celiac" => true,
    //     "available" => true,
    //     "cover_image" => "images/cibo_9.jpg",
    //     'category_id' => 2,
    //     'restaurant_id' => 3,
    // ],
    // [
    //     "name" => "Pappardelle al ragù",
    //     "price" => 12,
    //     "description" => "Macinato di carne, Pomodoro fresco, pasta fatta in casa",
    //     "vegan" => false,
    //     "celiac" => false,
    //     "available" => true,
    //     "cover_image" => "images/cibo_1.jpg",
    //     'category_id' => 2,
    //     'restaurant_id' => 2,
    // ],
    // [
    //     "name" => "Spaghetti con le Vongole",
    //     "price" => 12,
    //     "description" => "Vongole fresche, aglio, prezzemolo e un tocco di peperoncino",
    //     "vegan" => false,
    //     "celiac" => false,
    //     "available" => true,
    //     "cover_image" => "images/cibo_11.jpg",
    //     'category_id' => 2,
    //     'restaurant_id' => 1,
    // ],
    // [
    //     "name" => "Cacio e Pepe",
    //     "price" => 10,
    //     "description" => "Semplice, tradizionale, con pecorino romano e pepe nero",
    //     "vegan" => false,
    //     "celiac" => false,
    //     "available" => true,
    //     "cover_image" => "images/cibo_3.jpg",
    //     'category_id' => 2,
    //     'restaurant_id' => 2,
    // ],
    // [
    //     "name" => "Pennette ai Funghi",
    //     "price" => 10,
    //     "description" => "Gustose, senza glutine, con varietà di funghi",
    //     "vegan" => true,
    //     "celiac" => true,
    //     "available" => true,
    //     "cover_image" => "images/cibo_32.jpg",
    //     'category_id' => 2,
    //     'restaurant_id' => 2,
    // ],

    // [
    //     "name" => "Grigliata Mista",
    //     "price" => 20,
    //     "description" => "Saporita e variegata, con carni e verdure alla brace",
    //     "vegan" => false,
    //     "celiac" => false,
    //     "available" => true,
    //     "cover_image" => "images/cibo_33.jpg",
    //     'category_id' => 3,
    //     'restaurant_id' => 1,
    // ],
    // [
    //     "name" => "Patate fritte",
    //     "price" => 6,
    //     "description" => "Croccanti, dorate, irresistibili",
    //     "vegan" => true,
    //     "celiac" => true,
    //     "available" => true,
    //     "cover_image" => "images/cibo_34.jpg",
    //     'category_id' => 4,
    //     'restaurant_id' => 1,
    // ],
    // [
    //     "name" => "Insalatona",
    //     "price" => 8,
    //     "description" => "Fresca, verde e variegata",
    //     "vegan" => true,
    //     "celiac" => true,
    //     "available" => true,
    //     "cover_image" => "images/cibo_35.jpg",
    //     'category_id' => 4,
    //     'restaurant_id' => 1,
    // ],

    // PIZZERIA

    // [
    //     "name" => "Pizza Margherita",
    //     "price" => 8,
    //     "description" => "Pomodoro, mozzarella, basilico, semplice e deliziosa",
    //     "vegan" => false,
    //     "celiac" => false,
    //     "available" => true,
    //     "cover_image" => "images/cibo_4.jpg",
    //     'category_id' => 2,
    //     'restaurant_id' => 7,
    // ],
    // [
    //     "name" => "Pizza senza Glutine",
    //     "price" => 10,
    //     "description" => "Base senza glutine, ingredienti freschissimi",
    //     "vegan" => true,
    //     "celiac" => true,
    //     "available" => true,
    //     "cover_image" => "images/cibo_5.jpg",
    //     'category_id' => 2,
    //     'restaurant_id' => 7,
    // ],
    // [
    //     "name" => "Pizza Diavola",
    //     "price" => 8,
    //     "description" => "Piccante, saporita, con peperoncino e salame",
    //     "vegan" => false,
    //     "celiac" => false,
    //     "available" => true,
    //     "cover_image" => "images/cibo_10.jpg",
    //     'category_id' => 2,
    //     'restaurant_id' => 7,
    // ],
    // [
    //     "name" => "Pizza Boscaiola",
    //     "price" => 10,
    //     "description" => "Saporita, ricca di funghi e salsiccia",
    //     "vegan" => false,
    //     "celiac" => false,
    //     "available" => true,
    //     "cover_image" => "images/cibo_17.jpg",
    //     'category_id' => 2,
    //     'restaurant_id' => 7,
    // ],
    // [
    //     "name" => "Pizza Green",
    //     "price" => 10,
    //     "description" => "Gustosa, senza ingredienti di origine animale",
    //     "vegan" => true,
    //     "celiac" => true,
    //     "available" => true,
    //     "cover_image" => "images/cibo_18.jpg",
    //     'category_id' => 2,
    //     'restaurant_id' => 7,
    // ],
    // [
    //     "name" => "Pizza Quattro Stagioni",
    //     "price" => 11,
    //     "description" => "Con prosciutto, olive, carciofi e funghi",
    //     "vegan" => false,
    //     "celiac" => false,
    //     "available" => true,
    //     "cover_image" => "images/cibo_19.jpg",
    //     'category_id' => 2,
    //     'restaurant_id' => 7,
    // ],
    // [
    //     "name" => "Supplì",
    //     "price" => 11,
    //     "description" => "L'antipasto perfetto per una pizza",
    //     "vegan" => false,
    //     "celiac" => false,
    //     "available" => true,
    //     "cover_image" => "images/cibo_39.jpg",
    //     'category_id' => 2,
    //     'restaurant_id' => 7,
    // ],

    // FAST FOOD

    // [
    //     "name" => "Hamburger",
    //     "price" => 8,
    //     "description" => "Gustoso, succulento, con carne di alta qualità",
    //     "vegan" => false,
    //     "celiac" => false,
    //     "available" => true,
    //     "cover_image" => "images/cibo_20.jpg",
    //     'category_id' => 3,
    //     'restaurant_id' => 5,
    // ],
    // [
    //     "name" => "Cheeseburger",
    //     "price" => 10,
    //     "description" => "Delizioso, con formaggio fuso cremosissimo",
    //     "vegan" => false,
    //     "celiac" => false,
    //     "available" => true,
    //     "cover_image" => "images/cibo_21.jpg",
    //     'category_id' => 3,
    //     'restaurant_id' => 5,
    // ],
    // [
    //     "name" => "Patate fritte",
    //     "price" => 6,
    //     "description" => "Croccanti, dorate, irresistibili",
    //     "vegan" => true,
    //     "celiac" => true,
    //     "available" => true,
    //     "cover_image" => "images/cibo_34.jpg",
    //     'category_id' => 4,
    //     'restaurant_id' => 1,
    // ],
    // [
    //     "name" => "Pizza Diavola",
    //     "price" => 8,
    //     "description" => "Piccante, saporita, con peperoncino e salame",
    //     "vegan" => false,
    //     "celiac" => false,
    //     "available" => true,
    //     "cover_image" => "images/cibo_10.jpg",
    //     'category_id' => 2,
    //     'restaurant_id' => 7,
    // ],
    // [
    //     "name" => "Ciambelle",
    //     "price" => 5,
    //     "description" => "Farina, Latte, Zucchero, Olio di Semi",
    //     "vegan" => false,
    //     "celiac" => false,
    //     "available" => true,
    //     "cover_image" => "images/cibo_2.jpg",
    //     'category_id' => 5,
    //     'restaurant_id' => 2,
    // ],
    // [
    //     "name" => "Hamburger di Tofù",
    //     "price" => 9,
    //     "description" => "Hamburger di tofù con verdure, senza glutine",
    //     "vegan" => true,
    //     "celiac" => true,
    //     "available" => true,
    //     "cover_image" => "images/cibo_46.jpg",
    //     'category_id' => 3,
    //     'restaurant_id' => 5,
    // ],
